package com.papmobdev.domain.cars.usecaseslastconfigurationcar

import com.papmobdev.domain.FlowUseCaseOut
import com.papmobdev.domain.cars.models.LastCarConfigurationModel

interface GetConfigurationCarUseCase: FlowUseCaseOut<LastCarConfigurationModel>