package com.papmobdev.domain.cars.usecaseslastconfigurationcar

import com.papmobdev.domain.FlowUseCaseOut
import com.papmobdev.domain.cars.models.LastCarConfigurationModel
import kotlinx.coroutines.ExperimentalCoroutinesApi

@ExperimentalCoroutinesApi
interface ObserveConfigurationCarUseCase: FlowUseCaseOut<LastCarConfigurationModel>