package com.papmobdev.enginevibrationanalyzerkotlin.domain.tests

import com.papmobdev.enginevibrationanalyzerkotlin.data.entities.MeasurementEntity
import com.papmobdev.enginevibrationanalyzerkotlin.data.entities.TestEntity
import com.papmobdev.enginevibrationanalyzerkotlin.domain.FlowUseCase
import kotlinx.coroutines.ExperimentalCoroutinesApi

@ExperimentalCoroutinesApi
interface GetMeasurementUseCase : FlowUseCase<TestEntity, List<MeasurementEntity>>